function T = make_summary_tables(rows, outDir, baseName)
%MAKE_SUMMARY_TABLES  Build a MATLAB table from per-case result rows and export
%   it to CSV, MAT and a LaTeX tabular (appendix-ready).
%
%       rows     : struct array; each scalar/string field becomes a column.
%       outDir   : destination folder (created if needed).
%       baseName : file stem; writes <baseName>.csv/.mat/.tex.
%
%   Returns the assembled table T.

    T = struct2table(rows);
    if ~exist(outDir, 'dir'); mkdir(outDir); end

    csvPath = fullfile(outDir, [baseName '.csv']);
    matPath = fullfile(outDir, [baseName '.mat']);
    texPath = fullfile(outDir, [baseName '.tex']);

    writetable(T, csvPath);
    save(matPath, 'T');
    write_latex_table(T, texPath, baseName);
end

% ------------------------------------------------------------------------
function write_latex_table(T, texPath, label)
%WRITE_LATEX_TABLE  Minimal LaTeX tabular writer (no toolboxes needed).
    vnames = T.Properties.VariableNames;
    nCol   = numel(vnames);
    nRow   = height(T);

    fid = fopen(texPath, 'w');
    if fid < 0
        warning('make_summary_tables:fopen', 'Could not write %s', texPath);
        return;
    end
    cleanup = onCleanup(@() fclose(fid));

    fprintf(fid, '%% Auto-generated by make_summary_tables.m\n');
    fprintf(fid, '\\begin{table}[t]\\centering\n');
    fprintf(fid, '\\caption{%s}\\label{tab:%s}\n', ...
                 strrep(label, '_', '\_'), strrep(label, '_', '-'));
    fprintf(fid, '\\footnotesize\n');
    fprintf(fid, '\\begin{tabular}{%s}\\hline\n', repmat('l', 1, nCol));
    fprintf(fid, '%s\\\\ \\hline\n', strjoin(strrep(vnames, '_', '\_'), ' & '));

    for r = 1:nRow
        cells = cell(1, nCol);
        for c = 1:nCol
            v = T{r, c};
            if isnumeric(v)
                cells{c} = fmtnum(v);
            elseif iscell(v)
                cells{c} = sanitise(char(string(v{1})));
            else
                cells{c} = sanitise(char(string(v)));
            end
        end
        fprintf(fid, '%s\\\\\n', strjoin(cells, ' & '));
    end

    fprintf(fid, '\\hline\\end{tabular}\n\\end{table}\n');
end

% ------------------------------------------------------------------------
function s = fmtnum(v)
    if v == 0
        s = '0';
    elseif abs(v) >= 1e4 || abs(v) < 1e-3
        s = sprintf('%.3g', v);
    else
        s = sprintf('%.4g', v);
    end
end

% ------------------------------------------------------------------------
function s = sanitise(s)
%SANITISE  Escape the LaTeX-special characters that may appear in labels.
    s = strrep(s, '\', '\textbackslash ');
    s = strrep(s, '_', '\_');
    s = strrep(s, '%', '\%');
    s = strrep(s, '&', '\&');
end
